version: '3'

services:
  rest-service:
    build: flask
    networks:
      - mynet
    ports:
      - 8000:8080
    depends_on:
      - postgres
    # command: >
    #   sh -c "sleep 10 && /usr/bin/python /game-store/initAlechemy.py"


  postgres:
    image: postgres:latest
    networks:
      - mynet
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
      - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      # - POSTGRES_DB=practica
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432

networks:
  mynet:
    driver: bridge
