version: '3'

services:
  rest-service:
    build: flask
    networks:
      - mynet
    ports:
      - 8000:5000
    depends_on:
      - postgres

  postgres:
    container_name: my_postgres_container
    image: postgres:latest
    networks:
      - mynet
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_DB}
      - POSTGRES_DB=practica
    ports:
      - 5432:5432

volumes:
  postgres-data: 

networks:
  mynet:
    driver: bridge