version: '3'
services:
  web:
    build: flask
    ports:
      - '5002:5000'
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - type: bind
        source: ./flask
        # target: /app
