version: '3'

services:
  rest-service:
    build: flask
    networks:
      - mynet
    ports:
      - 8000:5000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    networks:
      - mynet
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
  
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_DB}
      - POSTGRES_DB=practica
    ports:
      - 5432:5432

networks:
  mynet:
    driver: bridge
